version: "3.4"

services:
  nodeApp1:
    build: ./nodeApp
    ports:
      - 5002:5000
    restart: on-failure
    volumes:
      - ./nodeApp:/app
      - /app/node_modules
  nodeApp2:
    build: ./nodeApp
    restart: on-failure
    volumes:
      - ./nodeApp:/app
      - /app/node_modules
    ports:
      - 5001:5000
