version: "3.4"

services:
  nodeApp1:
    build: ./nodeApp
    container_name: 'nodeApp1'
    ports:
      - 5002:5000
    restart: on-failure
    volumes:
      - ./nodeApp:/app
      - /app/node_modules
  nodeApp2:
    build: ./nodeApp
    container_name: 'nodeApp2'
    restart: on-failure
    volumes:
      - ./nodeApp:/app
      - /app/node_modules
    ports:
      - 5001:5000
  nginx-server:
    build: ./nginxApp
      container_name: 'nginx-server'
      ports:
        - 5000:80
      restart: on-failure
